name: endophynd
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - snakemake-minimal>=8.0
  - mamba
  - pyyaml>=6.0
  - pip:
    - typer>=0.12
    - rich>=13.0
